### ISSUE TITLE
circular import error example from introduction

### ISSUE THREAD

**Issue by zoidable** [JSS95/dawiq#61]
When I try to run the example from the introduction
```
from dataclasses import dataclass
from dawiq import dataclass2Widget
from PySide6.QtWidgets import QApplication
import sys

@dataclass
class DataClass:
    x: int
    y: bool

app = QApplication(sys.argv)
dataWidget = dataclass2Widget(DataClass)
dataWidget.show()
app.exec()
app.quit()
```
I get a circular import error: `ImportError: cannot import name 'dataclass2Widget' from partially initialized module 'dawiq' (most likely due to a circular import)`

**Comment by JSS95** [comment]
Hello. I failed to reproduce the error in my system. What is your Python version and on which path did you run the example?

**Comment by zoidable** [comment]
My bad, i guess i messed up my venv.
